#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import math
import os
import subprocess
import sys
from pathlib import Path
from xml.sax.saxutils import escape

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

from argon_couette_params import compute_state


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def default_sparta_binary() -> Path:
    return repo_root() / "external/sparta-src/src/spa_mac"


def default_case_dir(kn: float) -> Path:
    return repo_root() / f"runs/sparta_kn{kn:g}"


def recommend_setup(
    kn: float,
    length: float,
    temperature: float,
    wall_speed: float,
    cells_per_mfp: float,
    flight_fraction: float,
    physical_time: float,
) -> dict[str, float]:
    if cells_per_mfp <= 0.0:
        raise ValueError("cells_per_mfp must be positive")
    if flight_fraction <= 0.0:
        raise ValueError("flight_fraction must be positive")
    if physical_time <= 0.0:
        raise ValueError("physical_time must be positive")

    state = compute_state(kn, length, temperature, wall_speed)
    mean_free_path = state["mean_free_path_m"]

    dx_target = mean_free_path / cells_per_mfp
    xcells = max(1, math.ceil(length / dx_target))
    dx_actual = length / xcells

    dt_max = dx_actual / wall_speed
    dt_recommended = flight_fraction * dt_max
    nsteps = max(1, math.ceil(physical_time / dt_recommended))

    return {
        "cells_per_mean_free_path": cells_per_mfp,
        "dx_target_m": dx_target,
        "dx_actual_m": dx_actual,
        "dt_max_from_wall_speed_s": dt_max,
        "dt_recommended_s": dt_recommended,
        "nsteps_recommended": nsteps,
        "physical_time_s": physical_time,
        "xcells": xcells,
    }


def build_case(
    *,
    kn: float,
    length: float,
    temperature: float,
    wall_speed: float,
    cells_per_mfp: float,
    flight_fraction: float,
    physical_time: float,
    streamwise_length: float | None,
    particles_per_cell: float,
    avg_fraction: float,
) -> dict[str, float]:
    rec = recommend_setup(
        kn,
        length,
        temperature,
        wall_speed,
        cells_per_mfp,
        flight_fraction,
        physical_time,
    )

    xcells = int(rec["xcells"])
    ycells = 1
    if streamwise_length is None:
        streamwise_length = rec["dx_actual_m"]

    state = compute_state(kn, length, temperature, wall_speed)
    domain_volume = length * streamwise_length
    target_particles = particles_per_cell * xcells * ycells
    fnum = state["number_density_per_m3"] * domain_volume / target_particles

    nsteps = int(rec["nsteps_recommended"])
    avg_window_steps = max(1, math.ceil(avg_fraction * nsteps))
    avg_start_step = nsteps - avg_window_steps + 1

    return {
        **state,
        **rec,
        "streamwise_length_m": streamwise_length,
        "ycells": ycells,
        "target_particles_per_cell": particles_per_cell,
        "target_total_sim_particles": target_particles,
        "fnum": fnum,
        "avg_fraction": avg_fraction,
        "avg_window_steps": avg_window_steps,
        "avg_start_step": avg_start_step,
    }


def write_input(case: dict[str, float], case_dir: Path, repo_root: Path) -> Path:
    species_file = Path("external/sparta-src/data/ar.species")
    collide_file = Path("external/sparta-src/data/ar.hs")
    species_rel_str = os.path.relpath(repo_root / species_file, case_dir)
    collide_rel_str = os.path.relpath(repo_root / collide_file, case_dir)

    text = f"""# Auto-generated by sparta/workflow.py
# Couette flow for argon using moving diffuse walls.

seed                12345
dimension           2
global              gridcut 0.0

boundary            s p p

create_box          0.0 {case["length_m"]:.12e} 0.0 {case["streamwise_length_m"]:.12e} -0.5 0.5
create_grid         {int(case["xcells"])} {int(case["ycells"])} 1
balance_grid        rcb cell

species             {species_rel_str} Ar
mixture             gas Ar nrho {case["number_density_per_m3"]:.12e} temp {case["temperature_K"]:.12e} vstream 0.0 0.0 0.0
collide             vss all {collide_rel_str}

surf_collide        lower diffuse {case["temperature_K"]:.12e} 1.0 translate 0.0 {-case["wall_speed_m_per_s"]:.12e} 0.0
surf_collide        upper diffuse {case["temperature_K"]:.12e} 1.0 translate 0.0 {case["wall_speed_m_per_s"]:.12e} 0.0
bound_modify        xlo collide lower
bound_modify        xhi collide upper

global              fnum {case["fnum"]:.12e}
create_particles    gas n 0

compute             flow grid all all nrho u v w massrho
compute             therm thermal/grid all all temp press
fix                 avg ave/grid all 1 {int(case["avg_window_steps"])} {int(case["nsteps_recommended"])} c_flow[*] c_therm[*]

dump                profile grid all {int(case["nsteps_recommended"])} profile.*.grid id xc yc vol f_avg[*]
dump_modify         profile format float %.12e
dump_modify         profile pad 8

stats               {max(1, min(5000, int(case["nsteps_recommended"] // 20) or 1))}
stats_style         step cpu np nattempt ncoll nbound nscoll

timestep            {case["dt_recommended_s"]:.12e}
run                 {int(case["nsteps_recommended"])}
"""

    input_path = case_dir / "in.couette"
    input_path.write_text(text, encoding="utf-8")
    return input_path


def write_case_files(
    *,
    repo_root: Path,
    case_dir: Path,
    kn: float,
    length: float,
    temperature: float,
    wall_speed: float,
    cells_per_mfp: float,
    flight_fraction: float,
    physical_time: float,
    streamwise_length: float | None,
    particles_per_cell: float,
    avg_fraction: float,
) -> tuple[Path, Path, dict[str, float]]:
    case_dir.mkdir(parents=True, exist_ok=True)
    case = build_case(
        kn=kn,
        length=length,
        temperature=temperature,
        wall_speed=wall_speed,
        cells_per_mfp=cells_per_mfp,
        flight_fraction=flight_fraction,
        physical_time=physical_time,
        streamwise_length=streamwise_length,
        particles_per_cell=particles_per_cell,
        avg_fraction=avg_fraction,
    )
    input_path = write_input(case, case_dir, repo_root)
    metadata_path = case_dir / "case.json"
    metadata_path.write_text(json.dumps(case, indent=2, sort_keys=True), encoding="utf-8")
    return input_path, metadata_path, case


def parse_grid_dump(path: Path) -> dict[str, object]:
    timestep: int | None = None
    number_of_cells: int | None = None
    columns: list[str] | None = None
    rows: list[list[float]] = []

    with path.open(encoding="utf-8") as handle:
        for raw_line in handle:
            line = raw_line.strip()
            if not line:
                continue
            if line == "ITEM: TIMESTEP":
                timestep = int(next(handle).strip())
                continue
            if line == "ITEM: NUMBER OF CELLS":
                number_of_cells = int(next(handle).strip())
                continue
            if line.startswith("ITEM: CELLS"):
                columns = line.split()[2:]
                continue
            if line.startswith("ITEM:"):
                continue
            if columns is None:
                continue
            values = line.split()
            if len(values) != len(columns):
                continue
            rows.append([float(value) for value in values])

    if columns is None or not rows:
        raise SystemExit(f"No SPARTA cell data found in '{path}'.")
    if number_of_cells is not None and number_of_cells != len(rows):
        raise SystemExit(
            f"Expected {number_of_cells} cells in '{path}', found {len(rows)} rows."
        )

    return {
        "timestep": timestep if timestep is not None else 0,
        "columns": columns,
        "rows": rows,
    }


def resolve_grid_path(raw_path: str) -> Path:
    path = Path(raw_path)
    if path.exists():
        return path.resolve()

    matches = sorted(Path.cwd().rglob(path.name))
    if len(matches) == 1:
        return matches[0].resolve()
    if matches:
        formatted_matches = "\n".join(f"  - {match}" for match in matches)
        raise SystemExit(
            f"Grid file '{raw_path}' was not found exactly, and multiple files named "
            f"'{path.name}' exist under {Path.cwd()}:\n{formatted_matches}\n"
            "Pass the intended file path explicitly."
        )
    raise SystemExit(f"Grid file '{raw_path}' was not found.")


def pick_column(columns: list[str] | dict[str, list[float]], candidates: list[str]) -> str:
    lowered = {name.lower(): name for name in columns}
    for candidate in candidates:
        if candidate.lower() in lowered:
            return lowered[candidate.lower()]
    raise SystemExit(f"Could not find any of {candidates} in columns {list(columns)}.")


def build_edges(centers: list[float]) -> list[float]:
    if len(centers) == 1:
        return [centers[0] - 0.5, centers[0] + 0.5]
    centers = sorted(centers)
    edges = [centers[0] - 0.5 * (centers[1] - centers[0])]
    for left, right in zip(centers, centers[1:]):
        edges.append(0.5 * (left + right))
    edges.append(centers[-1] + 0.5 * (centers[-1] - centers[-2]))
    return edges


def format_numbers(values: list[float | int]) -> str:
    parts: list[str] = []
    for value in values:
        if isinstance(value, int):
            parts.append(str(value))
        else:
            parts.append(f"{value:.12e}")
    return " ".join(parts)


def get_timestep(path: Path) -> int:
    parsed = parse_grid_dump(path)
    timestep = parsed["timestep"]
    assert isinstance(timestep, int)
    return timestep


def find_latest_grid(case_dir: Path) -> Path:
    grids = sorted(case_dir.glob("profile.*.grid"))
    if not grids:
        raise SystemExit(f"No SPARTA grid dumps found in '{case_dir}'.")
    return max(grids, key=get_timestep)


def convert_dump_to_vtu(input_path: Path, output_path: Path) -> int:
    parsed = parse_grid_dump(input_path)
    columns = parsed["columns"]
    rows = parsed["rows"]
    timestep = parsed["timestep"]
    assert isinstance(columns, list)
    assert isinstance(rows, list)
    assert isinstance(timestep, int)

    x_name = pick_column(columns, ["xc", "x"])
    y_name = pick_column(columns, ["yc", "y"])
    x_index = columns.index(x_name)
    y_index = columns.index(y_name)

    x_centers = sorted({row[x_index] for row in rows})
    y_centers = sorted({row[y_index] for row in rows})
    x_edges = build_edges(x_centers)
    y_edges = build_edges(y_centers)

    cell_lookup: dict[tuple[int, int], list[float]] = {}
    x_lookup = {value: index for index, value in enumerate(x_centers)}
    y_lookup = {value: index for index, value in enumerate(y_centers)}
    for row in rows:
        ix = x_lookup[row[x_index]]
        iy = y_lookup[row[y_index]]
        cell_lookup[(ix, iy)] = row

    if len(cell_lookup) != len(rows):
        raise SystemExit(f"Duplicate cell centers found in '{input_path}'.")

    points: list[tuple[float, float, float]] = []
    for y in y_edges:
        for x in x_edges:
            points.append((x, y, 0.0))

    nx = len(x_centers)
    ny = len(y_centers)
    connectivity: list[int] = []
    offsets: list[int] = []
    types: list[int] = []
    cell_data: dict[str, list[float]] = {
        name: [] for name in columns if name.lower() not in {x_name.lower(), y_name.lower()}
    }

    point_stride = len(x_edges)
    offset = 0
    for iy in range(ny):
        for ix in range(nx):
            row = cell_lookup.get((ix, iy))
            if row is None:
                raise SystemExit(
                    f"Missing cell at structured index ({ix}, {iy}) in '{input_path}'."
                )
            p0 = iy * point_stride + ix
            p1 = p0 + 1
            p2 = p1 + point_stride
            p3 = p0 + point_stride
            connectivity.extend([p0, p1, p2, p3])
            offset += 4
            offsets.append(offset)
            types.append(9)
            for name, value in zip(columns, row):
                if name in cell_data:
                    cell_data[name].append(value)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    xml = [
        '<?xml version="1.0"?>',
        '<VTKFile type="UnstructuredGrid" version="0.1" byte_order="LittleEndian">',
        "  <UnstructuredGrid>",
        f'    <FieldData><DataArray type="Int32" Name="TIME_STEP" NumberOfTuples="1" format="ascii">{timestep}</DataArray></FieldData>',
        f'    <Piece NumberOfPoints="{len(points)}" NumberOfCells="{len(rows)}">',
        "      <Points>",
        '        <DataArray type="Float64" NumberOfComponents="3" format="ascii">',
        "          " + format_numbers([coord for point in points for coord in point]),
        "        </DataArray>",
        "      </Points>",
        "      <Cells>",
        '        <DataArray type="Int32" Name="connectivity" format="ascii">',
        "          " + format_numbers(connectivity),
        "        </DataArray>",
        '        <DataArray type="Int32" Name="offsets" format="ascii">',
        "          " + format_numbers(offsets),
        "        </DataArray>",
        '        <DataArray type="UInt8" Name="types" format="ascii">',
        "          " + format_numbers(types),
        "        </DataArray>",
        "      </Cells>",
        "      <CellData>",
    ]
    for name, values in cell_data.items():
        xml.extend(
            [
                f'        <DataArray type="Float64" Name="{escape(name)}" format="ascii">',
                "          " + format_numbers(values),
                "        </DataArray>",
            ]
        )
    xml.extend(
        [
            "      </CellData>",
            "    </Piece>",
            "  </UnstructuredGrid>",
            "</VTKFile>",
            "",
        ]
    )
    output_path.write_text("\n".join(xml), encoding="utf-8")
    return timestep


def plot_grid(
    *,
    grid_path: Path,
    output_dir: Path,
    length: float,
    wall_speed: float,
    prefix: str,
) -> None:
    cache_root = output_dir / ".plot_cache"
    mpl_config_dir = cache_root / "matplotlib"
    xdg_cache_home = cache_root / "xdg"
    mpl_config_dir.mkdir(parents=True, exist_ok=True)
    xdg_cache_home.mkdir(parents=True, exist_ok=True)
    os.environ["MPLCONFIGDIR"] = str(mpl_config_dir)
    os.environ["XDG_CACHE_HOME"] = str(xdg_cache_home)

    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ModuleNotFoundError as exc:
        raise SystemExit(
            "matplotlib is required for plotting. Install it with "
            "`python3 -m pip install --user matplotlib`."
        ) from exc

    parsed = parse_grid_dump(grid_path)
    columns = parsed["columns"]
    rows = parsed["rows"]
    assert isinstance(columns, list)
    assert isinstance(rows, list)

    data: dict[str, list[float]] = {name: [] for name in columns}
    for row in rows:
        for name, value in zip(columns, row):
            data[name].append(value)

    x_name = pick_column(data, ["xc", "x"])
    v_name = pick_column(data, ["f_avg[3]", "v"])
    t_name = pick_column(data, ["f_avg[6]", "temp", "temperature"])

    x_vals = data[x_name]
    v_vals = data[v_name]
    t_vals = data[t_name]
    expected_linear = [
        -wall_speed + 2.0 * (x / length) * wall_speed
        for x in x_vals
    ]
    v_deviation = [v - linear for v, linear in zip(v_vals, expected_linear)]

    output_dir.mkdir(parents=True, exist_ok=True)

    plt.figure(figsize=(6, 4))
    plt.plot(x_vals, v_vals, linewidth=2, label="SPARTA")
    plt.plot(x_vals, expected_linear, "--", linewidth=1.5, label="Linear no-slip")
    plt.xlabel("x [m]")
    plt.ylabel("v [m/s]")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.savefig(output_dir / f"{prefix}_velocity.png", dpi=200)
    plt.close()

    plt.figure(figsize=(6, 4))
    plt.plot(x_vals, v_deviation, linewidth=2)
    plt.xlabel("x [m]")
    plt.ylabel("v - v_linear [m/s]")
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(output_dir / f"{prefix}_velocity_deviation.png", dpi=200)
    plt.close()

    plt.figure(figsize=(6, 4))
    plt.plot(x_vals, t_vals, linewidth=2)
    plt.xlabel("x [m]")
    plt.ylabel("Temperature [K]")
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(output_dir / f"{prefix}_temperature.png", dpi=200)
    plt.close()


def run_sparta(sparta_binary: Path, case_dir: Path) -> None:
    if not sparta_binary.exists():
        raise SystemExit(f"SPARTA binary was not found at '{sparta_binary}'.")
    command = [str(sparta_binary), "-in", "in.couette"]
    subprocess.run(command, cwd=case_dir, check=True)


def maybe_plot_grid(
    *,
    grid_path: Path,
    output_dir: Path,
    length: float,
    wall_speed: float,
    prefix: str,
    required: bool,
) -> bool:
    try:
        plot_grid(
            grid_path=grid_path,
            output_dir=output_dir,
            length=length,
            wall_speed=wall_speed,
            prefix=prefix,
        )
        return True
    except SystemExit as exc:
        if required:
            raise
        print(f"Skipping plots: {exc}")
        return False


def add_common_case_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--kn", type=float, required=True)
    parser.add_argument("--length", type=float, default=1.0e-2)
    parser.add_argument("--temperature", type=float, default=300.0)
    parser.add_argument("--wall-speed", type=float, default=1000.0)
    parser.add_argument("--cells-per-mfp", type=float, default=1.0)
    parser.add_argument("--flight-fraction", type=float, default=0.5)
    parser.add_argument("--physical-time", type=float, default=8.0e-3)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="command", required=True)

    recommend_parser = subparsers.add_parser("recommend")
    add_common_case_arguments(recommend_parser)
    recommend_parser.add_argument("--json", action="store_true")

    case_parser = subparsers.add_parser("case")
    add_common_case_arguments(case_parser)
    case_parser.add_argument("--output-dir", type=Path)
    case_parser.add_argument("--streamwise-length", type=float)
    case_parser.add_argument("--particles-per-cell", type=float, default=40.0)
    case_parser.add_argument("--avg-fraction", type=float, default=0.5)

    run_parser = subparsers.add_parser("run")
    run_parser.add_argument("--case-dir", type=Path, required=True)
    run_parser.add_argument("--sparta-binary", type=Path, default=default_sparta_binary())

    vtk_parser = subparsers.add_parser("vtk")
    vtk_parser.add_argument("--grid", help="SPARTA grid dump path")
    vtk_parser.add_argument("--case-dir", type=Path, help="SPARTA case directory")
    vtk_parser.add_argument("--output", type=Path)

    plot_parser = subparsers.add_parser("plot")
    plot_parser.add_argument("--grid", help="SPARTA grid dump path")
    plot_parser.add_argument("--case-dir", type=Path, help="SPARTA case directory")
    plot_parser.add_argument("--output-dir", type=Path, required=True)
    plot_parser.add_argument("--length", type=float, default=1.0e-2)
    plot_parser.add_argument("--wall-speed", type=float, default=1000.0)
    plot_parser.add_argument("--prefix", default="sparta")

    all_parser = subparsers.add_parser("all")
    add_common_case_arguments(all_parser)
    all_parser.add_argument("--case-dir", type=Path)
    all_parser.add_argument("--sparta-binary", type=Path, default=default_sparta_binary())
    all_parser.add_argument("--streamwise-length", type=float)
    all_parser.add_argument("--particles-per-cell", type=float, default=40.0)
    all_parser.add_argument("--avg-fraction", type=float, default=0.5)
    all_parser.add_argument("--vtk-output", type=Path)
    all_parser.add_argument("--figures-dir", type=Path)
    all_parser.add_argument("--prefix", default="sparta")
    all_parser.add_argument(
        "--skip-plots",
        action="store_true",
        help="Run SPARTA and export VTU without generating matplotlib figures",
    )

    return parser


def command_recommend(args: argparse.Namespace) -> None:
    rec = recommend_setup(
        args.kn,
        args.length,
        args.temperature,
        args.wall_speed,
        args.cells_per_mfp,
        args.flight_fraction,
        args.physical_time,
    )
    if args.json:
        print(json.dumps(rec, indent=2, sort_keys=True))
        return
    for key, value in rec.items():
        if isinstance(value, float):
            print(f"{key:32s} = {value:.12e}")
        else:
            print(f"{key:32s} = {value}")


def command_case(args: argparse.Namespace, repo_root: Path) -> None:
    output_dir = args.output_dir.resolve() if args.output_dir else default_case_dir(args.kn)
    input_path, metadata_path, _ = write_case_files(
        repo_root=repo_root,
        case_dir=output_dir,
        kn=args.kn,
        length=args.length,
        temperature=args.temperature,
        wall_speed=args.wall_speed,
        cells_per_mfp=args.cells_per_mfp,
        flight_fraction=args.flight_fraction,
        physical_time=args.physical_time,
        streamwise_length=args.streamwise_length,
        particles_per_cell=args.particles_per_cell,
        avg_fraction=args.avg_fraction,
    )
    print(input_path)
    print(metadata_path)


def resolve_case_grid(case_dir: Path, grid: str | None) -> Path:
    if grid:
        return resolve_grid_path(grid)
    return find_latest_grid(case_dir)


def command_vtk(args: argparse.Namespace) -> None:
    case_dir = args.case_dir.resolve() if args.case_dir else Path.cwd()
    grid_path = resolve_case_grid(case_dir, args.grid)
    output = args.output.resolve() if args.output else case_dir / "sparta_profile.vtu"
    if output.suffix.lower() != ".vtu":
        raise SystemExit("--output must end with .vtu.")
    convert_dump_to_vtu(grid_path, output)
    print(output)


def command_plot(args: argparse.Namespace) -> None:
    case_dir = args.case_dir.resolve() if args.case_dir else Path.cwd()
    grid_path = resolve_case_grid(case_dir, args.grid)
    plot_grid(
        grid_path=grid_path,
        output_dir=args.output_dir.resolve(),
        length=args.length,
        wall_speed=args.wall_speed,
        prefix=args.prefix,
    )


def command_all(args: argparse.Namespace, repo_root: Path) -> None:
    case_dir = args.case_dir.resolve() if args.case_dir else default_case_dir(args.kn)
    input_path, metadata_path, _ = write_case_files(
        repo_root=repo_root,
        case_dir=case_dir,
        kn=args.kn,
        length=args.length,
        temperature=args.temperature,
        wall_speed=args.wall_speed,
        cells_per_mfp=args.cells_per_mfp,
        flight_fraction=args.flight_fraction,
        physical_time=args.physical_time,
        streamwise_length=args.streamwise_length,
        particles_per_cell=args.particles_per_cell,
        avg_fraction=args.avg_fraction,
    )
    print(input_path)
    print(metadata_path)

    run_sparta(args.sparta_binary.resolve(), case_dir)

    latest_grid = find_latest_grid(case_dir)
    vtk_output = args.vtk_output.resolve() if args.vtk_output else case_dir / "sparta_profile.vtu"
    convert_dump_to_vtu(latest_grid, vtk_output)
    print(vtk_output)

    if not args.skip_plots:
        figures_dir = args.figures_dir.resolve() if args.figures_dir else repo_root / "figures"
        if maybe_plot_grid(
            grid_path=latest_grid,
            output_dir=figures_dir,
            length=args.length,
            wall_speed=args.wall_speed,
            prefix=args.prefix,
            required=False,
        ):
            print(figures_dir)


def main() -> None:
    root = repo_root()
    parser = build_parser()
    args = parser.parse_args()

    if args.command == "recommend":
        command_recommend(args)
    elif args.command == "case":
        command_case(args, root)
    elif args.command == "run":
        run_sparta(args.sparta_binary.resolve(), args.case_dir.resolve())
    elif args.command == "vtk":
        command_vtk(args)
    elif args.command == "plot":
        command_plot(args)
    elif args.command == "all":
        command_all(args, root)


if __name__ == "__main__":
    main()
